env: "prod"

infra:
  url: "elschool.ru"

storage:
  driver: "postgres"
  host: "api-db"
  port: 5432
  dbname: "elschool_api_db"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"

cache:
  host: "api-cache"
  port: 6379
  base: 0

grpc:
  port: 44044
  timeout: 10h

metrics:
  address: "0.0.0.0:9090"
